COMMENT_AUTHOR = 'Cooper'
COMMENT_TEXT = 'This is a comment!'
DATETIME_PATTERN = '%Y%m%d%T'
BLOGGER_NAME = 'me'
BLOGGER_PASSWORD = 'password'
BLOG_TITLE = 'Hello!'
BLOG_AUTHOR = 'Cooper'
BLOG_ENTRY = 'I am a blog post! I would enjoy it if you read me!'
FIRST = 0